# ============================================================
#  Basic Site Settings
# ============================================================
title: "Brian Chu"
description: "Music Composer | Game Audio | Interactive Media"
url: "https://buraianchuu.github.io"
baseurl: ""  # Leave empty for main user site (username.github.io)

# ============================================================
#  Author Information
# ============================================================
author:
  name: "Brian Chu"
  email: "borongchu@gmail.com"
  github: "buraianchuu"
  linkedin: "brian-chu"
  location: "Edmonton, Canada"
  bio: "Composer and sound designer passionate about storytelling through sound and interactivity."

# ============================================================
#  Theme Settings
# ============================================================
theme: minima  

minima:
  skin: dark
  social_links:
    - platform: github
      user_url: "https://github.com/buraianchuu"
    - platform: linkedin
      user_url: "https://www.linkedin.com/in/brian-chu-a51701300/"
    - platform: youtube
      user_url: "https://www.youtube.com/@BRChu"

# ============================================================
#  Appearance
# ============================================================
markdown: kramdown
highlighter: rouge
show_excerpts: true
paginate: 5
paginate_path: "/page:num/"

# ============================================================
#  Custom Variables (for navigation or reuse)
# ============================================================
nav_items:
  - name: "Home"
    url: "/"
  - name: "Projects"
    url: "/projects/"
  - name: "Music"
    url: "/music/"
  - name: "Blog"
    url: "/blog/"
  - name: "About"
    url: "/about/"

# ============================================================
#  Plugins
# ============================================================
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# ============================================================
#  Build Settings
# ============================================================
exclude:
  - "node_modules"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"

# ============================================================
#  SEO and Social
# ============================================================
social:
  twitter: 
  github: 
  linkedin: 
  youtube: 
  email: 


