title: "Brian Chu"
description: "Music Composer | Game Audio | Interactive Media"
theme: minima
show_excerpts: true
markdown: kramdown
highlighter: rouge

<footer>
  © {{ site.author.name }}  
  <a href="mailto:{{ borongchu@gmail.com }}">Email</a> ·
  <a href="https://github.com/{{ buraianchuu }}">GitHub</a> ·
  <a href="https://linkedin.com/in/{{ brian-chu-a51701300 }}">LinkedIn</a>
</footer>


plugins:
  - jekyll-feed
  - jekyll-seo-tag
