title: "Brian Chu"
description: "Music Composer | Game Audio | Interactive Media"
theme: minima
show_excerpts: true
markdown: kramdown
highlighter: rouge

author:
  name: "Brian Chu"
  email: "borongchu@gmail.com"
  github: "buraianchuu"
  linkedin: "brian-chu"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
