# ============================================================
#  Basic Site Settings
# ============================================================
title: "Brian Chu"
description: "Music Composer | Game Audio | Interactive Media"
url: "https://yourusername.github.io"
baseurl: ""  # Leave empty for main user site (username.github.io)

# ============================================================
#  Author Information
# ============================================================
author:
  name: "Brian Chu"
  email: "youremail@example.com"
  github: "yourusername"
  linkedin: "your-linkedin-username"
  location: "Edmonton, Canada"
  bio: "Composer and sound designer passionate about storytelling through sound and interactivity."

# ============================================================
#  Theme Settings
# ============================================================
theme: minima  # you can also try "jekyll-theme-cayman" or "jekyll-theme-modernist"
# Optional: remove or replace with your custom theme

# Minima theme customization (if you use minima)
minima:
  skin: dark
  social_links:
    - platform: github
      user_url: "https://github.com/yourusername"
    - platform: linkedin
      user_url: "https://linkedin.com/in/your-linkedin-username"
    - platform: youtube
      user_url: "https://youtube.com/@yourchannel"

# ============================================================
#  Appearance
# ============================================================
markdown: kramdown
highlighter: rouge
show_excerpts: true
paginate: 5
paginate_path: "/page:num/"

# ============================================================
#  Custom Variables (for navigation or reuse)
# ============================================================
nav_items:
  - name: "Home"
    url: "/"
  - name: "Projects"
    url: "/projects/"
  - name: "Music"
    url: "/music/"
  - name: "Blog"
    url: "/blog/"
  - name: "About"
    url: "/about/"

# ============================================================
#  Plugins
# ============================================================
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-archives

# ============================================================
#  Build Settings
# ============================================================
exclude:
  - "node_modules"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"

# ============================================================
#  SEO and Social
# ============================================================
social:
  twitter: "your_twitter"
  github: "yourusername"
  linkedin: "your-linkedin-username"
  youtube: "yourchannel"
  email: "youremail@example.com"

# ============================================================
#  Google Analytics (optional)
# ============================================================
google_analytics: "G-XXXXXXXXXX"
