title: "Brian Chu"
description: "Music Composer | Game Audio | Interactive Media"
theme: minima
show_excerpts: true
markdown: kramdown
highlighter: rouge

author_name: "Brian Chu"
author_email: "borongchu@gmail.com"
author_github: "buraianchuu"
author_linkedin: "brian-chu"



plugins:
  - jekyll-feed
  - jekyll-seo-tag
